snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_SNOWFLAKE_DEMO
      schema: PUBLIC
      account: JFAFBHE-CWC07645
      user: myfsnowflake001
